apply plugin: 'com.android.library'
ext {
    PUBLISH_GROUP_ID = 'istat.android.data.access.sqlite'
    PUBLISH_ARTIFACT_ID = 'istat-access-sqlite'
    PUBLISH_VERSION = '1.3.1'
}
apply from: 'release-jar.gradle'
dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    api 'com.google.code.gson:gson:2.3.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test:core:1.5.0'
    androidTestImplementation 'androidx.test:runner:1.5.2'
}

android {
    namespace 'istat.android.data.access.sqlite'
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileSdkVersion 34

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            res.srcDirs = ['src/main/res']
        }

        // Move the tests to tests/java, tests/res, etc...
       // instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
    task clearJar(type: Delete) {
        delete '../build/libs/sqlite-access.jar'
    }

    task makeJar(type: Copy) {
        from('build/intermediates/bundles/release/')
        into('../build/libs/')
        include('classes.jar')
        rename('classes.jar', 'sqlite-access.jar')
    }

    makeJar.dependsOn(clearJar, build)
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        abortOnError false
    }
}
